# Generated by Django 5.2.1 on 2025-05-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_rename_desciption_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='product_images',
            field=models.ManyToManyField(related_name='products', to='Order.productimage'),
        ),
    ]
